// Test fakes of @core/agents (`@core/agents/testing`). Explicit named re-exports only.

export {
  type AgentContextOverrides,
  buildAgentContextEntries,
  TEST_REQUEST_ID,
  TEST_TENANT,
  TEST_UID,
} from "./agent-context-fixture.ts";
export {
  createFakeAccessPort,
  createFakeApprovalPort,
  createFakeAuditPort,
  createFakeCommandIdempotency,
  createFakeCustomAgentsPort,
  createFakeFilesPort,
  createFakeFlagsPort,
  createFakeProjectCommands,
  createFakePromptStorePort,
  createFakeRuntimePorts,
  createFakeSettingsPort,
  createFakeUsagePort,
  createFakeUsageReportPort,
  createFakeWebContentPort,
  createFakeWorkflowApprovalPort,
  createFakeWorkflowCommandPort,
  createRecordingKnowledgeEvents,
  createRecordingNotificationPort,
  defaultAgentSettings,
  FAKE_REGIONAL,
  type FakeAccessPort,
  type FakeApprovalPort,
  type FakeAuditPort,
  type FakeCommandIdempotency,
  type FakeCustomAgentsPort,
  type FakeMembership,
  type FakeProjectCommands,
  type FakePromptStorePort,
  type FakeUsagePort,
  type FakeUsageReportPort,
  type FakeWorkflowApprovalPort,
  type FakeWorkflowCommandPort,
  grantHolderOf,
  type RecordingKnowledgeEvents,
  type RecordingNotificationPort,
} from "./fake-ports.ts";
