// Test fakes of @core/agents (`@core/agents/testing`). Explicit named re-exports only.
export {
  createFakeAccessPort,
  createFakeApprovalPort,
  createFakeAuditPort,
  createFakeCommandIdempotency,
  createFakeFilesPort,
  createFakeFlagsPort,
  createFakePromptStorePort,
  type FakePromptStorePort,
  createFakeProjectsPort,
  createFakeRuntimePorts,
  createFakeSettingsPort,
  createFakeUsagePort,
  createFakeWebContentPort,
  createFakeWorkflowApprovalPort,
  createFakeWorkflowCommandPort,
  type FakeWorkflowApprovalPort,
  type FakeWorkflowCommandPort,
  createRecordingKnowledgeEvents,
  createRecordingNotificationPort,
  createFakeUsageReportPort,
  type FakeUsageReportPort,
  type RecordingNotificationPort,
  defaultAgentSettings,
  FAKE_REGIONAL,
  type FakeAccessPort,
  type FakeApprovalPort,
  type FakeAuditPort,
  type FakeCommandIdempotency,
  type FakeMembership,
  type FakeProjectsPort,
  type FakeUsagePort,
  grantHolderOf,
  type RecordingKnowledgeEvents,
} from "./fake-ports.ts";
export {
  type AgentContextOverrides,
  buildAgentContextEntries,
  TEST_REQUEST_ID,
  TEST_TENANT,
  TEST_UID,
} from "./agent-context-fixture.ts";
