/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ProfileSectionRouteImport } from './routes/profile/$section'
import { Route as OOrganizationIdIndexRouteImport } from './routes/o/$organizationId/index'
import { Route as OOrganizationIdPProjectIdIndexRouteImport } from './routes/o/$organizationId/p/$projectId/index'
import { Route as OOrganizationIdSettingsSectionSplatRouteImport } from './routes/o/$organizationId/settings/$section/$'
import { Route as OOrganizationIdSettingsMModuleIdRouteImport } from './routes/o/$organizationId/settings/m/$moduleId'
import { Route as OOrganizationIdPProjectIdChatChar123ConversationIdChar125RouteImport } from './routes/o/$organizationId/p/$projectId/chat/{-$conversationId}'
import { Route as OOrganizationIdPProjectIdMModuleIdSplatRouteImport } from './routes/o/$organizationId/p/$projectId/m/$moduleId/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSectionRoute = ProfileSectionRouteImport.update({
  id: '/profile/$section',
  path: '/profile/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrganizationIdIndexRoute = OOrganizationIdIndexRouteImport.update({
  id: '/o/$organizationId/',
  path: '/o/$organizationId/',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrganizationIdPProjectIdIndexRoute =
  OOrganizationIdPProjectIdIndexRouteImport.update({
    id: '/o/$organizationId/p/$projectId/',
    path: '/o/$organizationId/p/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OOrganizationIdSettingsSectionSplatRoute =
  OOrganizationIdSettingsSectionSplatRouteImport.update({
    id: '/o/$organizationId/settings/$section/$',
    path: '/o/$organizationId/settings/$section/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const OOrganizationIdSettingsMModuleIdRoute =
  OOrganizationIdSettingsMModuleIdRouteImport.update({
    id: '/o/$organizationId/settings/m/$moduleId',
    path: '/o/$organizationId/settings/m/$moduleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OOrganizationIdPProjectIdChatChar123ConversationIdChar125Route =
  OOrganizationIdPProjectIdChatChar123ConversationIdChar125RouteImport.update({
    id: '/o/$organizationId/p/$projectId/chat/{-$conversationId}',
    path: '/o/$organizationId/p/$projectId/chat/{-$conversationId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const OOrganizationIdPProjectIdMModuleIdSplatRoute =
  OOrganizationIdPProjectIdMModuleIdSplatRouteImport.update({
    id: '/o/$organizationId/p/$projectId/m/$moduleId/$',
    path: '/o/$organizationId/p/$projectId/m/$moduleId/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/organizations': typeof OrganizationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/profile/$section': typeof ProfileSectionRoute
  '/o/$organizationId/': typeof OOrganizationIdIndexRoute
  '/o/$organizationId/settings/$section/$': typeof OOrganizationIdSettingsSectionSplatRoute
  '/o/$organizationId/settings/m/$moduleId': typeof OOrganizationIdSettingsMModuleIdRoute
  '/o/$organizationId/p/$projectId/': typeof OOrganizationIdPProjectIdIndexRoute
  '/o/$organizationId/p/$projectId/chat/{-$conversationId}': typeof OOrganizationIdPProjectIdChatChar123ConversationIdChar125Route
  '/o/$organizationId/p/$projectId/m/$moduleId/$': typeof OOrganizationIdPProjectIdMModuleIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/organizations': typeof OrganizationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/profile/$section': typeof ProfileSectionRoute
  '/o/$organizationId': typeof OOrganizationIdIndexRoute
  '/o/$organizationId/settings/$section/$': typeof OOrganizationIdSettingsSectionSplatRoute
  '/o/$organizationId/settings/m/$moduleId': typeof OOrganizationIdSettingsMModuleIdRoute
  '/o/$organizationId/p/$projectId': typeof OOrganizationIdPProjectIdIndexRoute
  '/o/$organizationId/p/$projectId/chat/{-$conversationId}': typeof OOrganizationIdPProjectIdChatChar123ConversationIdChar125Route
  '/o/$organizationId/p/$projectId/m/$moduleId/$': typeof OOrganizationIdPProjectIdMModuleIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/organizations': typeof OrganizationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/profile/$section': typeof ProfileSectionRoute
  '/o/$organizationId/': typeof OOrganizationIdIndexRoute
  '/o/$organizationId/settings/$section/$': typeof OOrganizationIdSettingsSectionSplatRoute
  '/o/$organizationId/settings/m/$moduleId': typeof OOrganizationIdSettingsMModuleIdRoute
  '/o/$organizationId/p/$projectId/': typeof OOrganizationIdPProjectIdIndexRoute
  '/o/$organizationId/p/$projectId/chat/{-$conversationId}': typeof OOrganizationIdPProjectIdChatChar123ConversationIdChar125Route
  '/o/$organizationId/p/$projectId/m/$moduleId/$': typeof OOrganizationIdPProjectIdMModuleIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/organizations'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/profile/$section'
    | '/o/$organizationId/'
    | '/o/$organizationId/settings/$section/$'
    | '/o/$organizationId/settings/m/$moduleId'
    | '/o/$organizationId/p/$projectId/'
    | '/o/$organizationId/p/$projectId/chat/{-$conversationId}'
    | '/o/$organizationId/p/$projectId/m/$moduleId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/organizations'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/profile/$section'
    | '/o/$organizationId'
    | '/o/$organizationId/settings/$section/$'
    | '/o/$organizationId/settings/m/$moduleId'
    | '/o/$organizationId/p/$projectId'
    | '/o/$organizationId/p/$projectId/chat/{-$conversationId}'
    | '/o/$organizationId/p/$projectId/m/$moduleId/$'
  id:
    | '__root__'
    | '/'
    | '/invite'
    | '/organizations'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/profile/$section'
    | '/o/$organizationId/'
    | '/o/$organizationId/settings/$section/$'
    | '/o/$organizationId/settings/m/$moduleId'
    | '/o/$organizationId/p/$projectId/'
    | '/o/$organizationId/p/$projectId/chat/{-$conversationId}'
    | '/o/$organizationId/p/$projectId/m/$moduleId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteRoute: typeof InviteRoute
  OrganizationsRoute: typeof OrganizationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ProfileSectionRoute: typeof ProfileSectionRoute
  OOrganizationIdIndexRoute: typeof OOrganizationIdIndexRoute
  OOrganizationIdSettingsSectionSplatRoute: typeof OOrganizationIdSettingsSectionSplatRoute
  OOrganizationIdSettingsMModuleIdRoute: typeof OOrganizationIdSettingsMModuleIdRoute
  OOrganizationIdPProjectIdIndexRoute: typeof OOrganizationIdPProjectIdIndexRoute
  OOrganizationIdPProjectIdChatChar123ConversationIdChar125Route: typeof OOrganizationIdPProjectIdChatChar123ConversationIdChar125Route
  OOrganizationIdPProjectIdMModuleIdSplatRoute: typeof OOrganizationIdPProjectIdMModuleIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$section': {
      id: '/profile/$section'
      path: '/profile/$section'
      fullPath: '/profile/$section'
      preLoaderRoute: typeof ProfileSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$organizationId/': {
      id: '/o/$organizationId/'
      path: '/o/$organizationId'
      fullPath: '/o/$organizationId/'
      preLoaderRoute: typeof OOrganizationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$organizationId/p/$projectId/': {
      id: '/o/$organizationId/p/$projectId/'
      path: '/o/$organizationId/p/$projectId'
      fullPath: '/o/$organizationId/p/$projectId/'
      preLoaderRoute: typeof OOrganizationIdPProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$organizationId/settings/$section/$': {
      id: '/o/$organizationId/settings/$section/$'
      path: '/o/$organizationId/settings/$section/$'
      fullPath: '/o/$organizationId/settings/$section/$'
      preLoaderRoute: typeof OOrganizationIdSettingsSectionSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$organizationId/settings/m/$moduleId': {
      id: '/o/$organizationId/settings/m/$moduleId'
      path: '/o/$organizationId/settings/m/$moduleId'
      fullPath: '/o/$organizationId/settings/m/$moduleId'
      preLoaderRoute: typeof OOrganizationIdSettingsMModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$organizationId/p/$projectId/chat/{-$conversationId}': {
      id: '/o/$organizationId/p/$projectId/chat/{-$conversationId}'
      path: '/o/$organizationId/p/$projectId/chat/{-$conversationId}'
      fullPath: '/o/$organizationId/p/$projectId/chat/{-$conversationId}'
      preLoaderRoute: typeof OOrganizationIdPProjectIdChatChar123ConversationIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$organizationId/p/$projectId/m/$moduleId/$': {
      id: '/o/$organizationId/p/$projectId/m/$moduleId/$'
      path: '/o/$organizationId/p/$projectId/m/$moduleId/$'
      fullPath: '/o/$organizationId/p/$projectId/m/$moduleId/$'
      preLoaderRoute: typeof OOrganizationIdPProjectIdMModuleIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteRoute: InviteRoute,
  OrganizationsRoute: OrganizationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ProfileSectionRoute: ProfileSectionRoute,
  OOrganizationIdIndexRoute: OOrganizationIdIndexRoute,
  OOrganizationIdSettingsSectionSplatRoute:
    OOrganizationIdSettingsSectionSplatRoute,
  OOrganizationIdSettingsMModuleIdRoute: OOrganizationIdSettingsMModuleIdRoute,
  OOrganizationIdPProjectIdIndexRoute: OOrganizationIdPProjectIdIndexRoute,
  OOrganizationIdPProjectIdChatChar123ConversationIdChar125Route:
    OOrganizationIdPProjectIdChatChar123ConversationIdChar125Route,
  OOrganizationIdPProjectIdMModuleIdSplatRoute:
    OOrganizationIdPProjectIdMModuleIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
