import { z } from "zod";

/**
 * Audited actions (SP1 spec §6.7): SCREAMING_SNAKE, past tense, a consumed fact
 * (contracts/events.md §3.1). Denied platform and impersonation attempts use
 * `outcome: "denied"` on the `*_DENIED` actions.
 */
export const AUDIT_ACTIONS = [
  "ORGANIZATION_CREATED",
  "ORGANIZATION_UPDATED",
  "ORGANIZATION_DELETED",
  "PROJECT_CREATED",
  "PROJECT_UPDATED",
  "PROJECT_DELETED",
  "UNIT_CREATED",
  "UNIT_UPDATED",
  "UNIT_MOVED",
  "UNIT_DELETED",
  "ROLE_CREATED",
  "ROLE_UPDATED",
  "ROLE_DELETED",
  "MEMBERSHIP_GRANTED",
  "MEMBERSHIP_UPDATED",
  "MEMBERSHIP_REVOKED",
  "MEMBER_REMOVED",
  "INVITATION_CREATED",
  "INVITATION_ACCEPTED",
  "INVITATION_REVOKED",
  "API_KEY_CREATED",
  "API_KEY_REVOKED",
  "DEVICE_ACTIVATION_CREATED",
  "DEVICE_ACTIVATED",
  "DEVICE_REVOKED",
  "ACTIVE_ORGANIZATION_CHANGED",
  "SESSION_REVOKED",
  "ALL_SESSIONS_REVOKED",
  "DESKTOP_SESSION_REUSE_DETECTED",
  "IMPERSONATION_STARTED",
  "IMPERSONATION_ENDED",
  "IMPERSONATED_REQUEST_SERVED",
  "IMPERSONATED_WRITE_DENIED",
  "APPROVAL_REQUESTED",
  "APPROVAL_APPROVED",
  "APPROVAL_REJECTED",
  "APPROVAL_EXECUTED",
  "APPROVAL_FAILED",
  "PLATFORM_STAFF_GRANTED",
  "PLATFORM_ACCESS_DENIED",
  // Agent runtime (SP3 spec §8.1, §8.3, §11): SP3 adds action names only, the writer stays SP1's.
  "AGENT_TOOL_EXECUTED",
  "SEMANTIC_QUERY_EXECUTED",
  "KNOWLEDGE_DOCUMENT_INDEXED",
] as const;

export const AuditActionSchema = z.enum(AUDIT_ACTIONS);
export type AuditAction = z.infer<typeof AuditActionSchema>;
