-- Usage rollups, budget alerts and ledger export cursors (SP5 Task 6, generated by drizzle-kit
-- from usage/adapters/driven/drizzle-schema.ts). Expand-only. Rollback: see 0009.
CREATE TABLE "usage"."budget_alerts" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"tenant_id" text NOT NULL,
	"month" date NOT NULL,
	"threshold_percent" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "budget_alerts_tenant_month_threshold_key" UNIQUE("tenant_id","month","threshold_percent"),
	CONSTRAINT "budget_alerts_threshold_check" CHECK ("usage"."budget_alerts"."threshold_percent" IN (80, 100))
);
--> statement-breakpoint
ALTER TABLE "usage"."budget_alerts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "usage"."daily_rollups" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"tenant_id" text NOT NULL,
	"day" date NOT NULL,
	"model" text NOT NULL,
	"agent_id" text NOT NULL,
	"calls" bigint NOT NULL,
	"input_tokens" bigint NOT NULL,
	"output_tokens" bigint NOT NULL,
	"cost_micro_usd" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "daily_rollups_tenant_day_model_agent_key" UNIQUE("tenant_id","day","model","agent_id"),
	CONSTRAINT "daily_rollups_counts_check" CHECK ("usage"."daily_rollups"."calls" >= 0 AND "usage"."daily_rollups"."input_tokens" >= 0 AND "usage"."daily_rollups"."output_tokens" >= 0 AND "usage"."daily_rollups"."cost_micro_usd" >= 0)
);
--> statement-breakpoint
ALTER TABLE "usage"."daily_rollups" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "usage"."export_cursors" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"tenant_id" text NOT NULL,
	"exported_until" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "export_cursors_tenant_key" UNIQUE("tenant_id")
);
--> statement-breakpoint
ALTER TABLE "usage"."export_cursors" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "budget_alerts_tenant_rows" ON "usage"."budget_alerts" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));--> statement-breakpoint
CREATE POLICY "daily_rollups_tenant_rows" ON "usage"."daily_rollups" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));--> statement-breakpoint
CREATE POLICY "export_cursors_tenant_rows" ON "usage"."export_cursors" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));