-- Agent runs of the usage ledger (decision 0066, generated by drizzle-kit from
-- usage/adapters/driven/drizzle-schema.ts): one row per non-internal agent run and the guardrail
-- that stopped it, the source of the overview tripwire rate. Expand-only. Rollback: see 0013.
CREATE TABLE "usage"."agent_runs" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"request_id" text,
	"trace_id" text,
	"tenant_id" text NOT NULL,
	"user_id" text,
	"agent_id" text NOT NULL,
	"tripwire_processor_id" text,
	"occurred_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "agent_runs_trace_id_check" CHECK ("usage"."agent_runs"."trace_id" IS NULL OR "usage"."agent_runs"."trace_id" ~ '^[0-9a-f]{32}$')
);
--> statement-breakpoint
ALTER TABLE "usage"."agent_runs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "agent_runs_tenant_occurred_idx" ON "usage"."agent_runs" USING btree ("tenant_id","occurred_at");--> statement-breakpoint
CREATE POLICY "agent_runs_tenant_rows" ON "usage"."agent_runs" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true));