import type { FilePurpose } from "@core/contracts";

/**
 * Upload policy of the `files` context (umbrella §16.2, SP3 Task 13): which
 * media types each purpose accepts, the size cap of each type, and how the
 * bytes must look for the declared type. Pure: no I/O.
 */

export type FileCategory = "image" | "document" | "video" | "audio";

const MIB = 1024 * 1024;

/** Allowed declared media types and the size cap of each category. */
export const FILE_CATEGORIES: Readonly<Record<FileCategory, { readonly maxBytes: number; readonly contentTypes: readonly string[] }>> = {
  image: { maxBytes: 10 * MIB, contentTypes: ["image/png", "image/jpeg", "image/webp", "image/gif"] },
  document: { maxBytes: 25 * MIB, contentTypes: ["application/pdf", "text/plain", "text/markdown", "text/csv", "application/json"] },
  video: { maxBytes: 200 * MIB, contentTypes: ["video/mp4", "video/webm", "video/quicktime"] },
  audio: { maxBytes: 10 * MIB, contentTypes: ["audio/webm", "audio/ogg", "audio/mp4", "audio/wav"] },
};

/** Chat attachments take every category; the knowledge base only documents it can extract text from. */
export const PURPOSE_CATEGORIES: Readonly<Record<FilePurpose, readonly FileCategory[]>> = {
  "chat-attachment": ["image", "document", "video", "audio"],
  knowledge: ["document"],
};

export type UploadRule = { readonly category: FileCategory; readonly contentType: string; readonly maxBytes: number };

export type UploadRejectionReason = "TYPE_NOT_ALLOWED" | "TOO_LARGE";

export type UploadCheck =
  | { readonly ok: true; readonly rule: UploadRule }
  | { readonly ok: false; readonly reason: UploadRejectionReason; readonly field: "contentType" | "sizeBytes" };

/** `Text/Markdown; charset=utf-8` → `text/markdown`. */
export const normalizeContentType = (contentType: string): string => (contentType.split(";")[0] ?? "").trim().toLowerCase();

/** The rule for a declared type under a purpose, or `null` when the purpose does not accept it. */
export const resolveUploadRule = (purpose: FilePurpose, contentType: string): UploadRule | null => {
  const normalized = normalizeContentType(contentType);
  for (const category of PURPOSE_CATEGORIES[purpose]) {
    const { maxBytes, contentTypes } = FILE_CATEGORIES[category];
    if (contentTypes.includes(normalized)) return { category, contentType: normalized, maxBytes };
  }
  return null;
};

/** Checks a declared upload before any URL is signed. */
export const checkUpload = (input: { purpose: FilePurpose; contentType: string; sizeBytes: number }): UploadCheck => {
  const rule = resolveUploadRule(input.purpose, input.contentType);
  if (rule === null) return { ok: false, reason: "TYPE_NOT_ALLOWED", field: "contentType" };
  if (input.sizeBytes > rule.maxBytes) return { ok: false, reason: "TOO_LARGE", field: "sizeBytes" };
  return { ok: true, rule };
};

// What magic-byte detection (`file-type`) reports for each declared binary type.
// WebM and MP4 containers do not tell audio from video, so the audio types accept both.
const DETECTED_TYPES: Readonly<Record<string, readonly string[]>> = {
  "image/png": ["image/png"],
  "image/jpeg": ["image/jpeg"],
  "image/webp": ["image/webp"],
  "image/gif": ["image/gif"],
  "application/pdf": ["application/pdf"],
  "video/mp4": ["video/mp4"],
  "video/webm": ["video/webm"],
  "video/quicktime": ["video/quicktime"],
  "audio/webm": ["audio/webm", "video/webm"],
  "audio/ogg": ["audio/ogg", "audio/opus"],
  "audio/mp4": ["audio/mp4", "audio/x-m4a", "video/mp4"],
  "audio/wav": ["audio/wav", "audio/vnd.wave", "audio/x-wav"],
};

/** Types without magic bytes: they must decode as UTF-8 text with no NUL byte. */
const TEXT_TYPES: ReadonlySet<string> = new Set(["text/plain", "text/markdown", "text/csv", "application/json"]);

const isUtf8Text = (sample: Uint8Array): boolean => {
  if (sample.includes(0)) return false;
  try {
    // `stream: true` tolerates a multi-byte character cut at the end of the sample.
    new TextDecoder("utf-8", { fatal: true }).decode(sample, { stream: true });
    return true;
  } catch {
    // TypeError: the bytes are not valid UTF-8, nothing else throws here.
    return false;
  }
};

/**
 * Whether the first bytes of an object match its declared type.
 * @param detected media type reported by magic-byte detection, `undefined` when unknown.
 * @param sample the first bytes of the object (64 KiB is plenty).
 */
export const contentMatchesDeclared = (input: { declared: string; detected: string | undefined; sample: Uint8Array }): boolean => {
  const declared = normalizeContentType(input.declared);
  if (TEXT_TYPES.has(declared)) return input.detected === undefined && isUtf8Text(input.sample);
  if (input.detected === undefined) return false;
  return DETECTED_TYPES[declared]?.includes(normalizeContentType(input.detected)) ?? false;
};

/** Object path of a file: generated by the server, never taken from the client. */
export const storagePathOf = (file: { tenantId: string; id: string }): string => `tenants/${file.tenantId}/files/${file.id}`;

const STORAGE_PATH = /^tenants\/([^/]+)\/files\/([^/]+)$/;

/** Parses `tenants/{tenantId}/files/{fileId}`; `null` for any other object. */
export const parseStoragePath = (path: string): { tenantId: string; fileId: string } | null => {
  const match = STORAGE_PATH.exec(path);
  return match === null ? null : { tenantId: match[1] ?? "", fileId: match[2] ?? "" };
};

/** Previewable types are served inline; everything else downloads as an attachment. */
export const dispositionOf = (contentType: string): "inline" | "attachment" => {
  const category = normalizeContentType(contentType).split("/")[0];
  return category === "image" || category === "video" || category === "audio" ? "inline" : "attachment";
};
