// Public API of @core/services. Explicit named re-exports only (no `export *`).

// Re-exported for operator scripts (`pnpm platform:grant-staff`), which depend on services only.
// Re-exported for `pnpm seed:local`, which parses the ids it passes to the use cases.
export {
  OrganizationIdSchema,
  PLATFORM_ROLES,
  type PlatformRole,
  PlatformRoleSchema,
  ProjectIdSchema,
  UnitIdSchema,
  UserIdSchema,
} from "@core/contracts";
// SP1 access core: authorize() and its read model (SP3 reuses both).
// SP1 access write side (Task 9): grants, custom roles, projections, claims.
// SP1 members and invitations (Task 11).
// SP1 four-eyes approval requests (Task 17): SP3 registers `agent-command`, SP5 its workflow handler.
// Functions: the approval trigger test writes SP1 requests through the same adapter.
export {
  type AccessCore,
  AccessDeniedError,
  type AccessDeps,
  AccessNotFoundError,
  type AccessProjectionStore,
  type AccessReaderCall,
  type AccessReaders,
  type AccessServices,
  type AccessWriteDeps,
  type ApiKeyStatusRecord,
  type ApprovalActionContext,
  type ApprovalActionHandler,
  type ApprovalHandlerRegistry,
  type ApprovalServices,
  AppUrlMissingError,
  type Authorize,
  type AuthorizeDecision,
  type AuthorizeRequest,
  assertNoEscalation,
  buildAccessProjection,
  type ChainNode,
  type ChainUnit,
  ClaimsTooLargeError,
  type ClaimsWriter,
  CORE_CLAIM_KEYS,
  CORE_PERMISSION_SOURCE,
  type CoreClaims,
  type CustomRoleRecord,
  chainNodeIds,
  checkNodeChain,
  computeEffectivePermissions,
  createAccessCore,
  createAccessServices,
  createApprovalHandlerRegistry,
  createApprovalServices,
  createFirebaseUserDirectory,
  createFirestoreAccessAdapters,
  createFirestoreApprovalRequestRepository,
  createFirestoreInvitationRepository,
  createInMemoryAccessStore,
  createInMemoryAccessWriteStore,
  createInMemoryInvitationRepository,
  createMemberServices,
  createNoopInvitationNotifier,
  createPermissionRegistry,
  createRequestScope,
  type DenyReason,
  type DeviceStatusRecord,
  type EffectivePermissions,
  type EffectivePermissionsRequest,
  type EffectivePermissionsResult,
  EmailMismatchError,
  type EscalationCheck,
  EscalationForbiddenError,
  type FirestoreAccessAdapters,
  type GetEffectivePermissions,
  type GrantMembership,
  type GrantMembershipCommand,
  type GrantPlan,
  type GrantReader,
  type GrantRecord,
  type GrantSource,
  type ImpersonationSessionRecord,
  type InMemoryAccessStore,
  InvitationAlreadyUsedError,
  InvitationExpiredError,
  type InvitationNotifier,
  type InvitationRepository,
  isNodeWithin,
  LastOwnerError,
  type MemberDeps,
  type MemberServices,
  MembershipExistsError,
  type MembershipRepository,
  makeAuthorize,
  makeGetEffectivePermissions,
  makeSyncClaims,
  type NodeChain,
  type NodeChainReader,
  normalizeEmail,
  type PermissionRegistry,
  PermissionRegistryError,
  type PermissionRegistryErrorCode,
  type PermissionSource,
  type PlatformStaffRecord,
  type PrepareGrantArgs,
  type PrincipalStatusReader,
  type RequestAccess,
  type RequestApproval,
  RoleInUseError,
  type RoleReader,
  type RoleRepository,
  type SyncClaims,
  UnknownPermissionError,
  UnknownRoleError,
  type UserAccessVersionStore,
  type UserDirectory,
  type UserStatusRecord,
} from "./services/access/index.ts";
export { createInMemoryPromptRepository } from "./services/agents/adapters/driven/in-memory-prompt-repository.ts";
export { createMastraPromptEvalGateway } from "./services/agents/adapters/driven/mastra-prompt-eval-gateway.ts";
export {
  createPostgresPromptRepository,
  PLATFORM_PROMPT_SCOPE,
  PROMPTS_RUNTIME_ROLE,
} from "./services/agents/adapters/driven/postgres-prompt-repository.ts";
export {
  AGENT_SETTINGS_PERMISSIONS,
  buildAgentSettingsRoutes,
} from "./services/agents/adapters/driving/agent-settings-route-handler.ts";
// SP5 prompt store (Task 9, decision 0038): append-only Postgres versions and activations, eval gate.
export { buildPromptRoutes, PROMPT_PERMISSIONS } from "./services/agents/adapters/driving/prompts-route-handler.ts";
export type { PromptEvalError, PromptEvalGateway } from "./services/agents/application/ports/prompt-eval-gateway.ts";
export type {
  ActivePrompts,
  PromptKey,
  PromptRepository,
} from "./services/agents/application/ports/prompt-repository.ts";
// SP3 agents context: the /v1 → Mastra gateway (Task 8).
// SP3 core MCP server entry `/v1/mcp` (Task 24).
// SP3 agent commands: the SP1 `agent-command` approval handler and command idempotency (follow-up #26).
export {
  AGENT_COMMAND_HANDLER_KIND,
  type AgentCallScope,
  type AgentCommandApprovalDeps,
  AgentCommandError,
  type AgentCommandErrorCode,
  type AgentCommandExecution,
  type AgentCommandExecutor,
  type AgentCommandExecutorSpec,
  type AgentCommandExecutors,
  type AgentMessage,
  type AgentRunInput,
  type AgentRunOptions,
  type AgentRuntimeGateway,
  agentCommandExecutors,
  buildMcpRoutes,
  buildVoiceRoutes,
  CHAT_ROUTES,
  type ChatRuntimeGateway,
  type ChatStreamAnswer,
  CORE_MCP_SERVER,
  CommandContractError,
  type CommandContractErrorCode,
  type CommandIdempotency,
  type CommandPreview,
  type CommandRun,
  type CommandRunResult,
  type ContractCommand,
  type ContractCommandSpec,
  CREATE_PROJECT_COMMAND_ID,
  createAgentCommandApprovalHandler,
  createCommandIdempotency,
  createCoreAgentCommandExecutors,
  createMastraChatGateway,
  createMastraGateway,
  createMastraVoiceGateway,
  createServerlessIdTokenSource,
  DEFAULT_GATEWAY_TIMEOUTS,
  DuplicateCommandError,
  defineAgentCommandExecutor,
  defineContractCommand,
  type GatewayError,
  type GatewayErrorCode,
  type GatewayResult,
  type GatewayStream,
  gatewayErrorResponse,
  type IdTokenMinter,
  type MastraGatewayOptions,
  MCP_REQUEST_HEADERS,
  MCP_USE_PERMISSION,
  type McpCallInput,
  type McpGatewayResponse,
  mapMastraStatus,
  mcpHeadersOf,
  registerAgentCommandApprovals,
  ServerlessIdTokenError,
  type ServerlessIdTokenSource,
  type ThreadInput,
  type ToolCallDecisionInput,
  type VoiceRoutesDeps,
  type VoiceRuntimeGateway,
  type WorkflowResumeInput,
  type WorkflowStartInput,
} from "./services/agents/index.ts";
export {
  createPostgresPromptServices,
  createPromptServices,
  type PromptServices,
} from "./services/agents/prompt-composition.ts";
// SP1 tenant audit log listing (Task 18): the SP5 audit viewer.
// SP1 audit writer, rate limiter and idempotency store (Task 7).
export {
  AUDIT_LOG_COLLECTIONS,
  AUDIT_LOG_SCHEMA_VERSION,
  type AuditActor,
  type AuditEntryRejectedCode,
  AuditEntryRejectedError,
  type AuditLogAppend,
  type AuditLogServices,
  type AuditLogWriter,
  type AuditRecordInput,
  type AuditServices,
  type AuditTransaction,
  type AuditWriter,
  auditActorOf,
  createAuditServices,
  createFirestoreAuditLogServices,
  createFirestoreAuditLogWriter,
  createInMemoryAuditLogWriter,
  type InMemoryAuditLogWriter,
  type ListAuditLogs,
  makeRecordAudit,
  type PlatformAuditRecordInput,
  type TenantAuditRecordInput,
} from "./services/audit/index.ts";
// SP3 catalog context: semantic view registry and read-only SQL runner (Task 11).
export {
  createBigQuerySemanticRunner,
  createPostgresSemanticRunner,
  createSemanticViewRegistry,
  DEFAULT_SEMANTIC_LIMIT,
  DEFAULT_STATEMENT_TIMEOUT_MS,
  type GuardedSql,
  guardConnectorSql,
  guardSemanticSql,
  InvalidSemanticViewError,
  MAX_SEMANTIC_LIMIT,
  MAX_SEMANTIC_PARAMS,
  MAX_SQL_LENGTH,
  makeRunSemanticQuery,
  type RunSemanticQuery,
  type RunSemanticQueryError,
  type RunSemanticQueryInput,
  SEMANTIC_READER_ROLE,
  SEMANTIC_SCHEMA,
  type SemanticQueryPrincipal,
  type SemanticQueryResult,
  type SemanticQueryRows,
  type SemanticQueryRunner,
  type SemanticQueryScope,
  type SemanticRunnerFailure,
  type SemanticSqlGuard,
  type SemanticView,
  type SemanticViewRegistry,
  type SqlParam,
  type SqlRejection,
  type SqlRejectionReason,
  wrapWithLimit,
} from "./services/catalog/index.ts";
// SP3 connectors context (Task 21): tenant connectors, secret store, `/v1/.../connectors`.
export {
  buildConnectorsRoutes,
  CONNECTOR_READ_PERMISSION,
  CONNECTOR_WRITE_PERMISSION,
  CONNECTORS_COLLECTION,
  ConnectorNotFoundError,
  type ConnectorRepository,
  type ConnectorsCommand,
  type ConnectorsDeps,
  type ConnectorsServices,
  connectorHostIssues,
  connectorSecretName,
  createConnectorsServices,
  createFirebaseConnectorsServices,
  createFirestoreConnectorRepository,
  createInMemoryConnectorRepository,
  createInMemorySecretStore,
  createLazySecretManagerClient,
  createLocalSecretStore,
  createSecretManagerStore,
  createSecretStoreFor,
  InvalidConnectorError,
  LOCAL_SECRETS_COLLECTION,
  LocalSecretStoreOutsideLocalError,
  type SecretManagerClientLike,
  type SecretStore as ConnectorSecretStore,
} from "./services/connectors/index.ts";
export { createFirestoreDeletedConversationStore } from "./services/conversations/adapters/driven/firestore-deleted-conversation-store.ts";
export {
  createFirestoreMessageFeedbackStore,
  createInMemoryMessageFeedbackStore,
  MESSAGE_FEEDBACK_COLLECTION,
} from "./services/conversations/adapters/driven/firestore-message-feedback-store.ts";
export { buildFeedbackRoutes } from "./services/conversations/adapters/driving/feedback-route-handler.ts";
// SP5 maintenance workflows (Task 7): conversation purge and eval export.
export type {
  DeletedConversation,
  DeletedConversationStore,
} from "./services/conversations/application/ports/deleted-conversation-store.ts";
export {
  makePurgeDeletedConversations,
  PURGE_AFTER_DAYS,
  type PurgeDeletedConversations,
} from "./services/conversations/application/use-cases/purge-deleted-conversations.ts";
export { feedbackKeyOf } from "./services/conversations/application/use-cases/record-message-feedback.ts";
// SP4 conversations context (Tasks 4–6): chat conversation metadata, `/v1/chat` and `/v1/conversations`.
export {
  ACTIVE_RUN_TTL_MS,
  type ActiveRuns,
  buildChatRoutes,
  buildConversationsRoutes,
  buildSearchTokens,
  type ChatRoutesDeps,
  CONVERSATIONS_COLLECTION,
  type ConversationRepository,
  type ConversationsServices,
  createConversationsServices,
  createFirestoreConversationRepository,
  createFirestoreConversationsServices,
  createInMemoryConversationRepository,
  type InMemoryConversationRepository,
  MAX_ACTIVE_STREAMS_PER_TENANT,
  queryTokens,
} from "./services/conversations/index.ts";
// Tenant-defined agents and skills (decision 0046): `/v1/agents`, `/v1/skills`, the runtime reads.
export {
  ASSISTANT_CHAT_AGENT,
  buildCustomAgentsRoutes,
  buildCustomSkillsRoutes,
  CUSTOM_AGENTS_COLLECTION,
  CUSTOM_AGENTS_READ_PERMISSION,
  CUSTOM_AGENTS_WRITE_PERMISSION,
  CUSTOM_SKILLS_COLLECTION,
  CustomAgentNotFoundError,
  type CustomAgentRepository,
  type CustomAgentsCommand,
  type CustomAgentsDeps,
  type CustomAgentsRouteDeps,
  type CustomAgentsRuntimeReads,
  type CustomAgentsServices,
  type CustomAgentUsage,
  CustomLimitReachedError,
  type CustomLimitsReader,
  CustomSkillNameTakenError,
  CustomSkillNotFoundError,
  type CustomSkillRepository,
  createCustomAgentsServices,
  createFirebaseCustomAgentsServices,
  createFirestoreCustomAgentRepository,
  createFirestoreCustomSkillRepository,
  createInMemoryCustomAgentRepository,
  createInMemoryCustomSkillRepository,
  createPlanCustomLimitsReader,
  customLimitsOfPlan,
  fixedCustomLimits,
  InvalidCustomDefinitionError,
  type IsChatAgentEnabled,
} from "./services/custom-agents/index.ts";
export {
  type BigQueryEvalRunRow,
  createBigQueryEvalRunSink,
  createNoopEvalRunSink,
  EVAL_RUNS_TABLE,
  type EvalRunSink,
  type EvalRunsTableLike,
  toEvalRunRows,
} from "./services/evals/index.ts";
// SP3 files context: signed URL uploads and magic-byte validation (Task 13).
export {
  buildFilesRoutes,
  type CreateReadUrl,
  checkUpload,
  contentMatchesDeclared,
  createEmulatorUrlSigner,
  createFakeUrlSigner,
  createFilesServices,
  createFirebaseFilesServices,
  createFirestoreFileRepository,
  createGcsObjectStore,
  createGcsUrlSigner,
  createInMemoryFileRepository,
  createInMemoryObjectStore,
  createLogFileEventPublisher,
  createRecordingFileEvents,
  type DetectContentType,
  detectContentType,
  EmulatorSignerOutsideLocalError,
  FILE_CATEGORIES,
  FILES_COLLECTION,
  type FileCategory,
  type FileEventPublisher,
  type FileObjectStore,
  type FileRepository,
  type FileSettlement,
  type FilesAdapters,
  type FilesEnv,
  type FilesServices,
  type FileUploadedEvent,
  type FileUrlSigner,
  type FinalizedObject,
  type FinalizeOutcome,
  type FinalizeUpload,
  filesBucketOf,
  type GetFile,
  type GetReadyFile,
  makeCreateReadUrl,
  makeFinalizeUpload,
  makeGetFile,
  makeGetReadyFile,
  makeObjectFinalizedHandler,
  makeReadFileBytes,
  makeRequestUpload,
  type ObjectFinalizedData,
  PURPOSE_CATEGORIES,
  parseStoragePath,
  READ_URL_TTL_MS,
  type ReadFileBytes,
  type ReadFileBytesError,
  type RequestUpload,
  type RequestUploadError,
  resolveUploadRule,
  SNIFF_BYTES,
  type StorageBucket,
  storagePathOf,
  UPLOAD_URL_TTL_MS,
  type UploadRule,
} from "./services/files/index.ts";
// SP5 feature flags (Task 8, decision 0039): registry, Remote Config / Firestore stores, `/v1` routes.
export {
  buildAdminFlagsRoutes,
  buildFlagsRoutes,
  CORE_FLAGS,
  createFirebaseFlagsServices,
  createFlagStoresFor,
  createFlagsServices,
  createInMemoryFlagStores,
  type EnvironmentFlagValues,
  expiredFlags,
  FEATURE_FLAG_OVERRIDES_COLLECTION,
  FEATURE_FLAGS_COLLECTION,
  FLAG_PERMISSIONS,
  type FlagStores,
  type FlagsServices,
  findFlag,
  flagEnvironmentDefaults,
  type GetFlagValues,
  isFlagExpired,
  type RegisteredFlag,
  type RemoteConfigClient,
  remoteConfigParameterOf,
  type TenantFlagOverrides,
} from "./services/flags/index.ts";
export { createFirebaseUserAccountReader } from "./services/identity/adapters/driven/firebase-user-account-reader.ts";
export type { UserAccountReader } from "./services/identity/application/ports/driven/user-account-reader.ts";
// SP1 me vertical and the SP3 hook `resolveAccessContext` (Task 12).
// SP1 web and desktop sessions (Task 13).
// SP1 scoped API keys (Task 14).
// SP1 device activations and devices (Task 15).
// SP1 platform staff and read-only impersonation (Task 16): SP2 guards, SP5 /admin.
// SP1 /v1 pipeline and principal resolution (Task 8).
export {
  AccountMissingError,
  type AdminImpersonationRouteDeps,
  type AdminStaffRouteDeps,
  type ApiKeyAuthenticator,
  type ApiKeyRevoker,
  type ApiKeyServices,
  buildAdminImpersonationRoutes,
  buildAdminStaffRoutes,
  type CookieJar,
  createApiKeyServices,
  createDeviceServices,
  createFakeTokenVerifier,
  createFirebaseTokenVerifier,
  createIdentityServices,
  createInMemoryUserRepository,
  createPlatformServices,
  createSessionServices,
  type DeviceServices,
  type FakeTokenVerifier,
  type IdentityServices,
  type ImpersonatedRequest,
  ImpersonationNotFoundError,
  isApiKeyCredential,
  makeResolvePrincipal,
  makeSessionActions,
  makeSessionGuards,
  makeVerifyBearer,
  mapTokenToPrincipal,
  noopApiKeyRevoker,
  normalizeActivationCode,
  type PlatformServices,
  parseApiKey,
  parseBearer,
  type ResolveAccessContext,
  type ResolvedAccessContext,
  type ResolvePrincipal,
  type ResolvePrincipalDeps,
  refuseAllApiKeys,
  requiresRevocationCheck,
  SESSION_COOKIE_NAME,
  type SessionActionContext,
  type SessionActionResult,
  type SessionActions,
  type SessionGuards,
  type SessionServices,
  type StaffSessionGuardResult,
  type TokenVerifier,
  type UserRepository,
  type VerifiedToken,
  type VerifyBearer,
  type WebSessionGuardResult,
} from "./services/identity/index.ts";
// SP3 knowledge context: documents, chunks and search with tenant row security (Task 12).
export {
  buildKnowledgeDocumentsRoutes,
  buildKnowledgeSourcesRoutes,
  CHUNKS_V1_DIMENSIONS,
  type ChunkMatch,
  createKnowledgeServices,
  createLogKnowledgeEventPublisher,
  createPostgresKnowledgeRepository,
  type DeleteDocument,
  type DocumentPage,
  type DocumentRefInput,
  DocumentRefInputSchema,
  type GetDocument,
  InvalidEmbeddingError,
  KNOWLEDGE_DELETE_PERMISSION,
  KNOWLEDGE_INGEST_WORKFLOW,
  KNOWLEDGE_READ_PERMISSION,
  KNOWLEDGE_RUNTIME_ROLE,
  KNOWLEDGE_WRITE_PERMISSION,
  type KnowledgeDocumentIndexedEvent,
  type KnowledgeDocumentsServices,
  type KnowledgeInputError,
  type KnowledgeRepository,
  type KnowledgeServices,
  knowledgeChunksV1,
  knowledgeDocuments,
  type ListDocuments,
  type ListDocumentsInput,
  ListDocumentsInputSchema,
  MAX_CHUNKS_PER_DOCUMENT,
  MAX_SEARCH_NAMESPACES,
  MAX_SEARCH_TOP_K,
  MIN_CITATION_SCORE,
  makeDeleteDocument,
  makeGetDocument,
  makeListDocuments,
  makeRegisterDocument,
  makeReplaceDocumentChunks,
  makeSearchChunks,
  type NewChunk,
  type NewKnowledgeDocument,
  type RegisterDocument,
  type RegisterDocumentInput,
  RegisterDocumentInputSchema,
  type ReplaceDocumentChunks,
  type ReplaceDocumentChunksInput,
  ReplaceDocumentChunksInputSchema,
  type SearchChunks,
  type SearchChunksInput,
  SearchChunksInputSchema,
  toVectorLiteral,
  type UpsertedDocument,
} from "./services/knowledge/index.ts";
// SP2 module settings store (Task 9, decision 0015 §6).
export {
  buildModuleSettingsRoutes,
  createFirestoreModuleSettingsRepository,
  createFirestoreModuleSettingsServices,
  createInMemoryModuleSettingsRepository,
  createModuleSettingsRegistry,
  createModuleSettingsServices,
  type GetModuleSettings,
  type InMemoryModuleSettingsRepository,
  InvalidModuleSettingsError,
  MODULE_SETTINGS_COLLECTION,
  type ModuleSettingsDefinition,
  type ModuleSettingsKey,
  type ModuleSettingsRegistry,
  ModuleSettingsRegistryError,
  type ModuleSettingsRepository,
  type ModuleSettingsServices,
  moduleSettingsDefinitionsOf,
  moduleSettingsDocId,
  type StoredModuleSettings,
  UnknownModuleError,
  type UpdateModuleSettings,
  type UpdateModuleSettingsCommand,
} from "./services/modules/index.ts";
export { createMastraConsoleGateway } from "./services/observability/adapters/driven/mastra-traces-reader.ts";
// SP5 traces, evals and feedback (Task 11, decision 0040): the runtime's console routes behind /v1.
export {
  buildObservabilityRoutes,
  OBSERVABILITY_PERMISSIONS,
} from "./services/observability/adapters/driving/traces-route-handler.ts";
export type {
  ConsoleError,
  ConsoleGateway,
  ConsoleResult,
} from "./services/observability/application/ports/console-gateway.ts";
export { createObservabilityServices, type ObservabilityServices } from "./services/observability/composition.ts";
export { requireStaff, requireTenant } from "./services/platform/adapters/driving/console-guards.ts";
// SP5 staff console (Task 10, decisions 0039 and 0041): plans, organizations, budgets, agent settings.
// SP5 staff console operations (decision 0043): runs, schedules, connectors and local logs for `/admin`.
// SP5 admin gaps (decision 0044): staff user search and batched lookup over `users/{uid}`.
export {
  type AdminLogsRouteDeps,
  type AdminOperationsRouteDeps,
  type AdminRunsQuery,
  type AdminUserDirectory,
  type AdminUsersRouteDeps,
  AGENT_SETTINGS_COLLECTION,
  type AgentSettingsRepository,
  buildAdminLogsRoutes,
  buildAdminOperationsRoutes,
  buildAdminPlatformRoutes,
  buildAdminUsersRoutes,
  CONSOLE_PERMISSIONS,
  type ConsoleServices,
  createConsoleServices,
  createFirebaseConsoleServices,
  createFirestoreAdminUserDirectory,
  createFirestoreAgentSettingsRepository,
  createFirestoreModelSettingsRepository,
  createInMemoryAdminUserDirectory,
  createInMemoryConsoleStores,
  createInMemoryModelSettingsRepository,
  createMastraOperationsGateway,
  createPostgresConsoleUsage,
  defaultAgentSettingsOf,
  LOGS_PERMISSION,
  type LogLinesQuery,
  listLogLines,
  MODEL_SETTINGS_COLLECTION,
  type ModelSettingsRepository,
  OPERATIONS_PERMISSIONS,
  type OperationsError,
  type OperationsGateway,
  type OperationsResult,
  ORGANIZATION_PLANS_COLLECTION,
  PLANS_COLLECTION,
  type ScheduleAction,
  type StoredModelSettings,
  syncTenantBudget,
  USERS_PERMISSION,
} from "./services/platform/index.ts";
export { type Clock, fixedClock, isAtOrBefore, systemClock } from "./services/shared/clock/clock.ts";
export { sha256Hex } from "./services/shared/crypto/sha256.ts";
export { toEnvIssues } from "./services/shared/env/env-issues.ts";
export {
  type EnvIssue,
  InvalidEnvError,
} from "./services/shared/env/invalid-env-error.ts";
export { EnvKeyCollisionError, loadServicesEnvWith } from "./services/shared/env/load-services-env-with.ts";
export {
  loadServicesEnv,
  type ServicesEnv,
  ServicesEnvSchema,
} from "./services/shared/env/services-env.schema.ts";
export {
  createFirebaseAdmin,
  EmulatorOutsideLocalError,
  type FirebaseAdmin,
  type FirebaseAdminSdk,
  FirebaseProjectMismatchError,
} from "./services/shared/firebase/firebase-admin.ts";
export { SYSTEM_ACTOR } from "./services/audit/domain/audit-actor.ts";
export {
  type CreateAuditFields,
  type UpdateAuditFields,
  withCreateAudit,
  withUpdateAudit,
} from "./services/shared/firestore/audit-fields.ts";
export {
  type BackfillUserSearchNamesResult,
  backfillUserSearchNames,
} from "./services/shared/firestore/backfill-user-search-names.ts";
export { CORE_COLLECTIONS, CORE_SCHEMA_VERSION } from "./services/shared/firestore/collections.ts";
export { createContractConverter, toFirestoreUpdate } from "./services/shared/firestore/contract-converter.ts";
export { CorruptDocumentError } from "./services/shared/firestore/corrupt-document-error.ts";
export {
  initialSoftDeleteFields,
  notDeleted,
  type SoftDeleteFields,
  softDeleteFields,
} from "./services/shared/firestore/soft-delete.ts";
export { runInTransaction } from "./services/shared/firestore/transaction-runner.ts";
export {
  createFirestoreUnitOfWork,
  inMemoryUnitOfWork,
  type UnitOfWork,
} from "./services/shared/firestore/unit-of-work.ts";
export { USER_SEARCH_NAME_FIELD, userSearchFields } from "./services/shared/firestore/user-search-fields.ts";
export {
  apiError,
  type DomainErrorMapping,
  dataResponse,
  mapDomainError,
  noContentResponse,
} from "./services/shared/http/api-errors.ts";
export type { ApiHandler, ApiHandlerContext, EndpointPrincipal } from "./services/shared/http/api-handler-context.ts";
// List helpers for module `/v1` handlers (`?cursor&limit`, `meta.page`, hidden-node 404).
export { deniedResponse, invalidCursorResponse, listResponse, pageRequestOf } from "./services/shared/http/api-list.ts";
export { type ApiRouteDeps, operationName, withApiRoute } from "./services/shared/http/api-route.ts";
export { clientIpOf } from "./services/shared/http/client-ip.ts";
export {
  applyCorsHeaders,
  CorsOriginListSchema,
  type CorsPolicy,
  createCorsPolicy,
  isCorsPreflight,
  preflightResponse,
} from "./services/shared/http/cors.ts";
export { type ErrorDetail, type ErrorEnvelope, errorResponse } from "./services/shared/http/error-envelope.ts";
export { matchPathParams } from "./services/shared/http/path-params.ts";
export { type RouteContext, type RouteHandler, withRouteBoundary } from "./services/shared/http/route-boundary.ts";
export {
  createFirestoreIdempotencyStore,
  IDEMPOTENCY_RECORDS_COLLECTION,
} from "./services/shared/idempotency/firestore-idempotency-store.ts";
export {
  type IdempotencyBegin,
  type IdempotencyStore,
  idempotencyScopeKey,
  type StoredResponse,
} from "./services/shared/idempotency/idempotency-store.ts";
export { createInMemoryIdempotencyStore } from "./services/shared/idempotency/in-memory-idempotency-store.ts";
export { canonicalJson, hashRequest } from "./services/shared/idempotency/request-hash.ts";
export { LOG_BUFFER_CAPACITY, readProcessLogBuffer } from "./services/shared/observability/log-buffer.ts";
export {
  createLogger,
  type LogContext,
  type LogFields,
  type Logger,
  type LogLevel,
  type LogRecord,
  type LogSink,
} from "./services/shared/observability/logger.ts";
export {
  configureProcessLogger,
  processLogger,
  readProcessLogContext,
} from "./services/shared/observability/process-logger.ts";
export {
  REQUEST_ID_HEADER,
  resolveRequestId,
} from "./services/shared/observability/request-id.ts";
export { type CursorPosition, decodeCursor, encodeCursor } from "./services/shared/pagination/cursor.ts";
export {
  type Page,
  type PageRequest,
  pageFromOverfetch,
  pageMeta,
  paginateInMemory,
} from "./services/shared/pagination/page.ts";
export {
  type DatabaseTarget,
  parseDatabaseUrl,
  type SocketDatabaseTarget,
  socketFilePath,
  type TcpDatabaseTarget,
} from "./services/shared/postgres/database-url.ts";
export { aiSchema } from "./services/shared/postgres/drizzle-schemas.ts";
export {
  buildPostgresConnection,
  createPostgresClient,
  InvalidDatabaseUrlError,
  type PostgresConnection,
  type PostgresPoolOptions,
} from "./services/shared/postgres/postgres-client.ts";
export {
  InvalidNodeIdError,
  TenantContextMissingError,
  type TenantScope,
  withTenantTransaction,
} from "./services/shared/postgres/with-tenant-transaction.ts";
export {
  createFirestoreRateLimiter,
  RATE_LIMIT_BUCKETS_COLLECTION,
} from "./services/shared/rate-limit/firestore-rate-limiter.ts";
export { createInMemoryRateLimiter } from "./services/shared/rate-limit/in-memory-rate-limiter.ts";
export { rateLimitedResponse, rateLimitHeaders } from "./services/shared/rate-limit/rate-limit-headers.ts";
export {
  getRateLimitPolicy,
  RATE_LIMIT_POLICIES,
  type RateLimitPolicy,
  type RateLimitPolicyId,
  UnknownRateLimitPolicyError,
} from "./services/shared/rate-limit/rate-limit-policies.ts";
export {
  type RateLimitDecision,
  type RateLimiter,
  rateLimitBucketId,
} from "./services/shared/rate-limit/rate-limiter.ts";
export { err, ok, type Result } from "./services/shared/result/result.ts";
export { normalizeSearchText } from "./services/shared/text/search-text.ts";
export { listLiveOrganizationIds } from "./services/tenancy/adapters/driven/firestore-live-organization-ids.ts";
// SP1 tenancy (Task 10): organizations, projects, the unit tree, regional settings.
export {
  CORE_UNIT_TYPE_ID,
  CORE_UNIT_TYPES,
  createFirestoreTenancyAdapters,
  createInMemoryTenancyStore,
  createTenancyServices,
  createUnitTypeRegistry,
  type FirestoreTenancyAdapters,
  type InMemoryTenancyStore,
  InvalidUnitParentError,
  type InvalidUnitParentReason,
  type LoadNode,
  MAX_SUBTREE_REWRITE,
  type NodeDetails,
  type OrganizationRepository,
  type ProjectRepository,
  type ResolveNodeRegionalSettings,
  regionalSettingsAt,
  resolveRegionalSettings,
  SubtreeTooLargeError,
  type TenancyDeps,
  TenancyNotFoundError,
  type TenancyServices,
  type UnitRepository,
  type UnitTypeRegistry,
  UnitTypeRegistryError,
  UserAccountMissingError,
} from "./services/tenancy/index.ts";
// SP5 tenant settings (Task 14): the month usage summary of an organization.
export { buildUsageRoutes, USAGE_READ_PERMISSION } from "./services/usage/adapters/driving/usage-route-handler.ts";
export { resolveTenantCaps, selfCapWithin, type TenantCaps } from "./services/usage/domain/budget-policy.ts";
// SP3 usage context: LLM usage ledger, tenant budgets and the warehouse sink (Task 16).
// SP5 usage report (decision 0039): rollups, warehouse export, budget alerts; live tenant ids.
export {
  ALERT_THRESHOLD_PERCENT,
  BIGQUERY_INSERT_BATCH,
  type BigQueryLlmCallRow,
  type BigQueryTableLike,
  BUDGET_ALERT_THRESHOLDS,
  type Budget,
  type BudgetAlertThreshold,
  type BudgetDecision,
  BudgetTenantMissingError,
  type CheckTenantBudget,
  createBigQueryLlmCallsTable,
  createBigQueryUsageSink,
  createNoopUsageSink,
  createPostgresTraceCosts,
  createPostgresUsageReportRepository,
  createPostgresUsageRepository,
  createUsageServices,
  createUsageSink,
  DEFAULT_PLAN_BUDGET,
  evaluateBudget,
  type GetUsageSummary,
  type GetUsageSummaryInput,
  GetUsageSummaryInputSchema,
  LLM_CALLS_TABLE,
  MAX_LLM_CALLS_PER_BATCH,
  type ModelTotals,
  type MonthSpend,
  makeCheckTenantBudget,
  makeGetUsageSummary,
  makeRecordLlmCalls,
  makeReportTenantUsage,
  type RecordLlmCalls,
  type ReportTenantUsage,
  resolveBudget,
  type StoredBudget,
  type TenantUsageReport,
  toBigQueryRow,
  USAGE_RUNTIME_ROLE,
  type UsageReportRepository,
  type UsageRepository,
  type UsageServices,
  type UsageSink,
  type UsageTotals,
  type UsageValidationError,
  usageLlmCalls,
  usageTenantBudgets,
  utcMonthStart,
} from "./services/usage/index.ts";
// SP5 workflows: HITL on SP1 approval requests (decision 0036).
// SP5 workflow runs, progress stream and tenant schedules (decisions 0037, 0040).
export {
  type ApprovalUpdate,
  buildSchedulesRoutes,
  buildTenantCatalogRoutes,
  buildWorkflowRunStreamRoutes,
  buildWorkflowRunsRoutes,
  createMastraWorkflowApprovalSettler,
  createMastraWorkflowGateway,
  createWorkflowResumeApprovalHandler,
  DEFAULT_SETTLE_TIMEOUT_MS,
  type MastraWorkflowApprovalSettlerOptions,
  makeSettleOnApprovalUpdate,
  registerWorkflowApprovals,
  type SettleOnUpdateOutcome,
  type SettleOutcome,
  TRIGGER_SETTLED_STATUSES,
  WORKFLOW_RESUME_HANDLER_KIND,
  WORKFLOW_RUN_PERMISSIONS,
  WorkflowApprovalError,
  type WorkflowApprovalErrorCode,
  type WorkflowApprovalSettler,
  type WorkflowGatewayResult,
  type WorkflowRuntimeGateway,
} from "./services/workflows/index.ts";
