import { sql } from "drizzle-orm";
import { bigint, check, index, integer, pgPolicy, text, timestamp, unique, uuid } from "drizzle-orm/pg-core";
import { usageSchema } from "../../../shared/postgres/drizzle-schemas.ts";

/**
 * Usage ledger tables (SP3 spec §12, decision 0026): source of the Drizzle
 * migrations only; queries go through postgres.js in
 * `postgres-usage-repository.ts`. `FORCE ROW LEVEL SECURITY`, the
 * `usage.tenant_month_spend` view and the runtime role are in the custom
 * migration that follows the generated one.
 */

const currentTenant = sql`current_setting('app.tenant_id', true)`;

// A tenant reads and writes only its own rows; there are no shared platform rows here.
const tenantPolicy = (table: string) =>
  pgPolicy(`${table}_tenant_rows`, { for: "all", using: sql`tenant_id = ${currentTenant}`, withCheck: sql`tenant_id = ${currentTenant}` });

/** One model call (contract `usage.LlmCall`); append-only, written in batches by the ledger exporter. */
export const usageLlmCalls = usageSchema
  .table(
    "llm_calls",
    {
      // Generated by the exporter (uuidv7) so a retried batch or the BigQuery insertId stays the same row.
      id: uuid("id").primaryKey().default(sql`uuidv7()`),
      requestId: text("request_id"),
      traceId: text("trace_id"),
      tenantId: text("tenant_id").notNull(),
      userId: text("user_id"),
      agentId: text("agent_id").notNull(),
      provider: text("provider").notNull(),
      model: text("model").notNull(),
      inputTokens: integer("input_tokens").notNull(),
      outputTokens: integer("output_tokens").notNull(),
      cachedTokens: integer("cached_tokens").notNull().default(0),
      // Null when the model has no verified price (the token cap still applies).
      costMicroUsd: bigint("cost_micro_usd", { mode: "number" }),
      latencyMs: integer("latency_ms").notNull(),
      finishReason: text("finish_reason"),
      occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
      createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
      updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    },
    (table) => [
      index("llm_calls_tenant_occurred_idx").on(table.tenantId, table.occurredAt),
      check("llm_calls_tokens_check", sql`${table.inputTokens} >= 0 AND ${table.outputTokens} >= 0 AND ${table.cachedTokens} >= 0`),
      check("llm_calls_cost_check", sql`${table.costMicroUsd} IS NULL OR ${table.costMicroUsd} >= 0`),
      check("llm_calls_latency_check", sql`${table.latencyMs} >= 0`),
      check("llm_calls_trace_id_check", sql`${table.traceId} IS NULL OR ${table.traceId} ~ '^[0-9a-f]{32}$'`),
      tenantPolicy("llm_calls"),
    ],
  )
  .enableRLS();

/** Monthly hard caps of a tenant; a tenant without a row gets the plan default (`budget-policy.ts`). */
export const usageTenantBudgets = usageSchema
  .table(
    "tenant_budgets",
    {
      id: uuid("id").primaryKey().default(sql`uuidv7()`),
      tenantId: text("tenant_id").notNull(),
      monthlyMicroUsd: bigint("monthly_micro_usd", { mode: "number" }).notNull(),
      monthlyTokens: bigint("monthly_tokens", { mode: "number" }).notNull(),
      createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
      updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    },
    (table) => [
      unique("tenant_budgets_tenant_key").on(table.tenantId),
      check("tenant_budgets_caps_check", sql`${table.monthlyMicroUsd} >= 0 AND ${table.monthlyTokens} >= 0`),
      tenantPolicy("tenant_budgets"),
    ],
  )
  .enableRLS();
