import {
  ActivityIcon,
  AlertTriangleIcon,
  ArchiveIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  BellIcon,
  BotIcon,
  BoxesIcon,
  BuildingIcon,
  CalendarIcon,
  ChartColumnIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CircleCheckIcon,
  CircleXIcon,
  ClockIcon,
  CommandIcon,
  CopyIcon,
  CpuIcon,
  CreditCardIcon,
  DatabaseIcon,
  EllipsisIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FileTextIcon,
  FlagIcon,
  FolderIcon,
  FolderOpenIcon,
  GlobeIcon,
  HistoryIcon,
  HouseIcon,
  InboxIcon,
  InfoIcon,
  KeyRoundIcon,
  LanguagesIcon,
  LayersIcon,
  LayoutDashboardIcon,
  ListIcon,
  LockIcon,
  LogOutIcon,
  type LucideIcon,
  MessageSquareIcon,
  MonitorIcon,
  MoonIcon,
  NetworkIcon,
  PencilIcon,
  PlugIcon,
  PlusIcon,
  PuzzleIcon,
  RefreshCwIcon,
  ScrollTextIcon,
  SearchIcon,
  SettingsIcon,
  ShieldCheckIcon,
  ShieldIcon,
  SmartphoneIcon,
  SparklesIcon,
  SunIcon,
  TrashIcon,
  UserIcon,
  UserPlusIcon,
  UsersIcon,
  WalletIcon,
  WifiOffIcon,
  WorkflowIcon,
  XIcon,
} from "lucide-react";

/**
 * Icons addressable by name (module manifests and navigation items carry a name, not a component).
 * An allowlist keeps the bundle small and the vocabulary consistent (icones.html: lucide, 1.5–2 px
 * strokes); add a name here before using it in a manifest.
 */
export const ICONS = {
  activity: ActivityIcon,
  "alert-triangle": AlertTriangleIcon,
  archive: ArchiveIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  bell: BellIcon,
  bot: BotIcon,
  boxes: BoxesIcon,
  building: BuildingIcon,
  calendar: CalendarIcon,
  chart: ChartColumnIcon,
  check: CheckIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "circle-check": CircleCheckIcon,
  "circle-x": CircleXIcon,
  clock: ClockIcon,
  command: CommandIcon,
  copy: CopyIcon,
  cpu: CpuIcon,
  "credit-card": CreditCardIcon,
  database: DatabaseIcon,
  ellipsis: EllipsisIcon,
  "external-link": ExternalLinkIcon,
  eye: EyeIcon,
  "eye-off": EyeOffIcon,
  "file-text": FileTextIcon,
  flag: FlagIcon,
  folder: FolderIcon,
  "folder-open": FolderOpenIcon,
  globe: GlobeIcon,
  history: HistoryIcon,
  home: HouseIcon,
  inbox: InboxIcon,
  info: InfoIcon,
  key: KeyRoundIcon,
  languages: LanguagesIcon,
  layers: LayersIcon,
  "layout-dashboard": LayoutDashboardIcon,
  list: ListIcon,
  lock: LockIcon,
  "log-out": LogOutIcon,
  message: MessageSquareIcon,
  monitor: MonitorIcon,
  moon: MoonIcon,
  network: NetworkIcon,
  pencil: PencilIcon,
  plug: PlugIcon,
  plus: PlusIcon,
  puzzle: PuzzleIcon,
  refresh: RefreshCwIcon,
  "scroll-text": ScrollTextIcon,
  search: SearchIcon,
  settings: SettingsIcon,
  shield: ShieldIcon,
  "shield-check": ShieldCheckIcon,
  smartphone: SmartphoneIcon,
  sparkles: SparklesIcon,
  sun: SunIcon,
  trash: TrashIcon,
  user: UserIcon,
  "user-plus": UserPlusIcon,
  users: UsersIcon,
  wallet: WalletIcon,
  "wifi-off": WifiOffIcon,
  workflow: WorkflowIcon,
  x: XIcon,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export const isIconName = (name: string): name is IconName => Object.hasOwn(ICONS, name);
