/** Small AI catalog in the shape `pnpm contracts:catalog` writes (`docs/catalog/catalog.ai.json`). */
export const FIXTURE_AI_CATALOG = {
  catalogVersion: 1,
  contracts: [
    {
      id: "example.Note",
      name: "Note",
      context: "example",
      kind: "entity",
      description: "A short note written by a member.",
      pii: "personal",
      tenancyScope: "organization",
      permission: "example.note.read",
      relations: [{ field: "tenantId", target: "tenancy.Organization", type: "belongs-to" }],
      fields: [
        { name: "id", description: "Note id.", pii: "none", required: true },
        { name: "text", description: "Note body.", pii: "personal", required: true, examples: ["Call the supplier"] },
        { name: "authorId", description: "Author uid.", pii: "personal", required: true, ui: { widget: "hidden" } },
        { name: "secretToken", description: "Never in the AI catalog.", pii: "sensitive", required: false },
      ],
      examples: [{ id: "Xk2mQ9vLr3TnB7pWc1aZ", text: "Call the supplier", authorId: "uA1b2C3d4E5f6G7h8I9j" }],
      jsonSchema: { type: "object" },
    },
    {
      id: "example.CreateNoteCommand",
      name: "CreateNoteCommand",
      context: "example",
      kind: "command",
      description: "Creates a note.",
      pii: "personal",
      tenancyScope: "organization",
      permission: "example.note.create",
      relations: [],
      fields: [{ name: "text", description: "Note body.", pii: "personal", required: true }],
      examples: [{ text: "[redacted]" }],
      jsonSchema: { type: "object" },
    },
    {
      id: "billing.Invoice",
      name: "Invoice",
      context: "billing",
      kind: "entity",
      description: "An invoice (hidden without its permission).",
      pii: "none",
      tenancyScope: "organization",
      permission: "billing.invoice.read",
      relations: [],
      fields: [{ name: "id", description: "Invoice id.", pii: "none", required: true }],
      examples: [{ id: "inv-1" }],
      jsonSchema: { type: "object" },
    },
    {
      id: "tenancy.Organization",
      name: "Organization",
      context: "tenancy",
      kind: "entity",
      description: "An organization (no permission: structure visible to members).",
      pii: "none",
      tenancyScope: "organization",
      relations: [],
      fields: [{ name: "id", description: "Organization id.", pii: "none", required: true }],
      examples: [{ id: "Jd8sK2lPq0WnR5tYu3bV" }],
      jsonSchema: { type: "object" },
    },
  ],
};
