import { stringify } from "yaml";
import { sortKeysDeep, type JsonRecord } from "./stable-json.ts";

/**
 * Minimal OpenAPI 3.1 document: contracts as `components.schemas`. Paths stay
 * empty until `/v1` endpoints exist (they will declare their own operations).
 */
export const renderOpenApi = (schemas: ReadonlyMap<string, JsonRecord>): string => {
  const document = {
    openapi: "3.1.0",
    info: {
      title: "Core API",
      version: "1.0.0",
      description: "Generated by `pnpm contracts:catalog` from @core/contracts. Do not edit.",
    },
    jsonSchemaDialect: "https://json-schema.org/draft/2020-12/schema",
    paths: {},
    components: { schemas: sortKeysDeep(Object.fromEntries(schemas)) },
  };
  // YAML 1.1 output quotes strings a 1.1 parser would read as timestamps or booleans.
  return stringify(document, { lineWidth: 0, version: "1.1" });
};
