import type { CatalogEntry, CatalogField } from "./catalog-entry.ts";

const escapeCell = (text: string): string => text.replaceAll("|", "\\|").replaceAll("\n", " ");

const code = (text: string): string => `\`${text}\``;

const renderMetaTable = (entry: CatalogEntry): string[] => {
  const rows: [string, string][] = [
    ["Id", code(entry.id)],
    ["Kind", code(entry.kind)],
    ["PII", code(entry.pii)],
    ["Tenancy scope", code(entry.tenancyScope)],
  ];
  if (entry.permission !== undefined) rows.push(["Permission", code(entry.permission)]);
  if (entry.deprecated === true) rows.push(["Deprecated", "yes"]);
  return ["| Property | Value |", "|---|---|", ...rows.map(([label, value]) => `| ${label} | ${value} |`)];
};

const renderUi = (field: CatalogField): string => {
  if (field.ui === undefined) return "";
  return Object.entries(field.ui)
    .map(([key, value]) => `${key}: ${String(value)}`)
    .join(", ");
};

const renderFields = (fields: readonly CatalogField[]): string[] => {
  if (fields.length === 0) return ["_No top-level fields._"];
  return [
    "| Field | Required | PII | Description | UI |",
    "|---|---|---|---|---|",
    ...fields.map(
      (field) =>
        `| ${code(field.name)} | ${field.required ? "yes" : "no"} | ${code(field.pii)} | ${escapeCell(field.description)} | ${escapeCell(renderUi(field))} |`,
    ),
  ];
};

const renderRelations = (entry: CatalogEntry): string[] => {
  if (entry.relations.length === 0) return ["_None._"];
  return entry.relations.map(
    (relation) => `- ${code(relation.type)} ${code(relation.target)} via ${code(relation.field)}`,
  );
};

/** Human-readable page for one contract; generated, never edited by hand. */
export const renderContractMarkdown = (entry: CatalogEntry): string =>
  [
    `# ${entry.id}`,
    "",
    "<!-- Generated by `pnpm contracts:catalog`. Do not edit. -->",
    "",
    entry.description,
    "",
    ...renderMetaTable(entry),
    "",
    "## Fields",
    "",
    ...renderFields(entry.fields),
    "",
    "## Relations",
    "",
    ...renderRelations(entry),
    "",
    "## Examples",
    "",
    "```json",
    JSON.stringify(entry.examples, null, 2),
    "```",
    "",
    `JSON Schema: [${entry.name}.schema.json](./${entry.name}.schema.json)`,
    "",
  ].join("\n");
