import { stringify } from "yaml";
import type { EndpointDefinition } from "../../src/contracts/http/endpoint.ts";
import type { RegisteredContract } from "../../src/contracts/registry.ts";
import { buildOpenApiPaths } from "./openapi-paths.ts";
import { type JsonRecord, sortKeysDeep } from "./stable-json.ts";

export { findDanglingRefs } from "./openapi-paths.ts";

type OpenApiInput = {
  /** JSON Schema per contract id (`buildJsonSchemas`), rendered as components. */
  schemas: ReadonlyMap<string, JsonRecord>;
  contracts: readonly RegisteredContract[];
  endpoints: readonly EndpointDefinition[];
};

/**
 * OpenAPI 3.1 document: contracts as `components.schemas`, endpoint descriptors
 * as `paths`. Native z.toJSONSchema instead of zod-to-openapi: see
 * app/docs/decisions/0001-openapi-generation.md.
 */
export const buildOpenApiDocument = (input: OpenApiInput): JsonRecord => ({
  openapi: "3.1.0",
  info: {
    title: "Core API",
    version: "1.0.0",
    description: "Generated by `pnpm contracts:catalog` from @core/contracts. Do not edit.",
  },
  jsonSchemaDialect: "https://json-schema.org/draft/2020-12/schema",
  // Top-level keys keep the conventional OpenAPI order; nested keys are sorted.
  paths: sortKeysDeep(buildOpenApiPaths({ endpoints: input.endpoints, contracts: input.contracts })),
  components: sortKeysDeep({
    schemas: Object.fromEntries(input.schemas),
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        description: "Firebase ID token or API key; /v1 reads credentials only from Authorization: Bearer.",
      },
    },
  }),
});

/** The document as YAML (`docs/openapi/v1.yaml`). */
export const renderOpenApi = (input: OpenApiInput): string =>
  // YAML 1.1 output quotes strings a 1.1 parser would read as timestamps or booleans.
  stringify(buildOpenApiDocument(input), { lineWidth: 0, version: "1.1" });
